In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [18]:
df = pd.read_csv(r"C:\Users\ADITYA GUPTA\Downloads\Data\NFHS_5_India_Districts_Factsheet_Data.csv")

In [19]:
df.head(3)

,District Names,State/UT,Number of Households surveyed,Number of Women age 15-49 years interviewed,Number of Men age 15-54 years interviewed,Female population age 6 years and above who ever attended school (%),Population below age 15 years (%),"Sex ratio of the total population (females per 1,000 males)","Sex ratio at birth for children born in the last five years (females per 1,000 males)",Children under age 5 years whose birth was registered with the civil authority (%),...,Men age 15 years and above wih Mildly elevated blood pressure (Systolic 140-159 mm of Hg and/or Diastolic 90-99 mm of Hg) (%),Men age 15 years and above wih Moderately or severely elevated blood pressure (Systolic ?160 mm of Hg and/or Diastolic ?100 mm of Hg) (%),Men age 15 years and above wih Elevated blood pressure (Systolic ?140 mm of Hg and/or Diastolic ?90 mm of Hg) or taking medicine to control blood pressure (%),Women (age 30-49 years) Ever undergone a screening test for cervical cancer (%),Women (age 30-49 years) Ever undergone a breast examination for breast cancer (%),Women (age 30-49 years) Ever undergone an oral cavity examination for oral cancer (%),Women age 15 years and above who use any kind of tobacco (%),Men age 15 years and above who use any kind of tobacco (%),Women age 15 years and above who consume alcohol (%),Men age 15 years and above who consume alcohol (%)
0,Nicobars,Andaman & Nicobar Islands,882,764,125,78.0,23.0,973,927,98.0,...,32.9,11.1,47.0,13.4,13.2,5.4,63.5,76.8,29.6,64.5
1,North & Middle Andaman,Andaman & Nicobar Islands,874,789,108,82.7,19.8,950,844,100.0,...,22.6,6.0,32.2,1.7,0.3,15.8,46.8,70.5,5.1,45.3
2,South Andaman,Andaman & Nicobar Islands,868,844,134,84.7,21.0,967,935,96.5,...,17.9,6.1,26.9,1.3,0.7,8.0,19.6,50.8,1.7,32.8

In [20]:
df.shape

(707, 109)

In [22]:
important_cols = [

# Location
"District Names",
"State/UT",

# Demographics
" Sex ratio of the total population (females per 1,000 males)",

# Infrastructure
"Population living in households with electricity (%)",
"Population living in households that use an improved sanitation facility2 (%)",
"Households using clean fuel for cooking3 (%)",
"Households with any usual member covered under a health insurance/financing scheme (%)",

# Women Education & Social
"Women (age 15-49) who are literate4 (%)",
"Women (age 15-49)  with 10 or more years of schooling (%)",
"Women age 20-24 years married before age 18 years (%)",
"Women age 15-24 years who use hygienic methods of protection during their menstrual period5 (%)",

# Maternal & Child Health
"Institutional births (in the 5 years before the survey) (%)",
"Children age 12-23 months fully vaccinated based on information from either vaccination card or mother's recall11 (%)",

# Child Nutrition
"Children under 5 years who are stunted (height-for-age)18 (%)",
"Children under 5 years who are wasted (weight-for-height)18 (%)",
"Children under 5 years who are underweight (weight-for-age)18 (%)",

# Women Health
"Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%)",
"Women (age 15-49 years) who are overweight or obese (BMI ?25.0 kg/m2)21 (%)",
"All women age 15-49 years who are anaemic22 (%)",

# Lifestyle
"Women age 15 years and above who use any kind of tobacco (%)"
]

# Keep only these columns
df = df[important_cols]

# Check remaining columns
print(df.shape)

(707, 20)

In [24]:
df.head(3)

,District Names,State/UT,"Sex ratio of the total population (females per 1,000 males)",Population living in households with electricity (%),Population living in households that use an improved sanitation facility2 (%),Households using clean fuel for cooking3 (%),Households with any usual member covered under a health insurance/financing scheme (%),Women (age 15-49) who are literate4 (%),Women (age 15-49) with 10 or more years of schooling (%),Women age 20-24 years married before age 18 years (%),Women age 15-24 years who use hygienic methods of protection during their menstrual period5 (%),Institutional births (in the 5 years before the survey) (%),Children age 12-23 months fully vaccinated based on information from either vaccination card or mother's recall11 (%),Children under 5 years who are stunted (height-for-age)18 (%),Children under 5 years who are wasted (weight-for-height)18 (%),Children under 5 years who are underweight (weight-for-age)18 (%),Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%),Women (age 15-49 years) who are overweight or obese (BMI ?25.0 kg/m2)21 (%),All women age 15-49 years who are anaemic22 (%),Women age 15 years and above who use any kind of tobacco (%)
0,Nicobars,Andaman & Nicobar Islands,973,97.9,83.5,56.9,2.7,87.5,53.5,11.4,100.0,97.8,-64.2,21.6,15.7,24.6,8.2,39.1,38.3,63.5
1,North & Middle Andaman,Andaman & Nicobar Islands,950,93.2,86.4,61.3,2.1,84.0,41.0,15.4,100.0,97.7,*,27.0,27.0,42.8,8.6,35.9,62.1,46.8
2,South Andaman,Andaman & Nicobar Islands,967,99.6,89.3,91.9,1.2,86.7,57.5,17.1,98.2,99.5,-76.3,21.1,12.6,17.4,10.0,39.0,57.7,19.6

In [25]:
df.columns

Index(['District Names', 'State/UT',
       ' Sex ratio of the total population (females per 1,000 males)',
       'Population living in households with electricity (%)',
       'Population living in households that use an improved sanitation facility2 (%)',
       'Households using clean fuel for cooking3 (%)',
       'Households with any usual member covered under a health insurance/financing scheme (%)',
       'Women (age 15-49) who are literate4 (%)',
       'Women (age 15-49)  with 10 or more years of schooling (%)',
       'Women age 20-24 years married before age 18 years (%)',
       'Women age 15-24 years who use hygienic methods of protection during their menstrual period5 (%)',
       'Institutional births (in the 5 years before the survey) (%)',
       'Children age 12-23 months fully vaccinated based on information from either vaccination card or mother's recall11 (%)',
       'Children under 5 years who are stunted (height-for-age)18 (%)',
       'Children under 5 years who are wasted (weight-for-height)18 (%)',
       'Children under 5 years who are underweight (weight-for-age)18 (%)',
       'Women (age 15-49 years) whose Body Mass Index (BMI) is below normal (BMI <18.5 kg/m2)21 (%)',
       'Women (age 15-49 years) who are overweight or obese (BMI ?25.0 kg/m2)21 (%)',
       'All women age 15-49 years who are anaemic22 (%)',
       'Women age 15 years and above who use any kind of tobacco (%)'],
      dtype='str')

In [26]:
df.columns = [

    "District",
    "State",
    "Sex_Ratio",
    "Electricity",
    "Sanitation",
    "Clean_Fuel",
    "Health_Insurance",
    "Women_Literacy",
    "Women_Schooling",
    "Child_Marriage",
    "Menstrual_Hygiene",
    "Institutional_Births",
    "Vaccination",
    "Stunted",
    "Wasted",
    "Underweight",
    "Low_BMI",
    "Obese",
    "Anaemia",
    "Tobacco_Use"
]

print(df.columns)

Index(['District', 'State', 'Sex_Ratio', 'Electricity', 'Sanitation',
       'Clean_Fuel', 'Health_Insurance', 'Women_Literacy', 'Women_Schooling',
       'Child_Marriage', 'Menstrual_Hygiene', 'Institutional_Births',
       'Vaccination', 'Stunted', 'Wasted', 'Underweight', 'Low_BMI', 'Obese',
       'Anaemia', 'Tobacco_Use'],
      dtype='str')

In [27]:
df.to_csv("cleaned_nfhs_data.csv", index=False)

In [28]:
df.head(3)

,District,State,Sex_Ratio,Electricity,Sanitation,Clean_Fuel,Health_Insurance,Women_Literacy,Women_Schooling,Child_Marriage,Menstrual_Hygiene,Institutional_Births,Vaccination,Stunted,Wasted,Underweight,Low_BMI,Obese,Anaemia,Tobacco_Use
0,Nicobars,Andaman & Nicobar Islands,973,97.9,83.5,56.9,2.7,87.5,53.5,11.4,100.0,97.8,-64.2,21.6,15.7,24.6,8.2,39.1,38.3,63.5
1,North & Middle Andaman,Andaman & Nicobar Islands,950,93.2,86.4,61.3,2.1,84.0,41.0,15.4,100.0,97.7,*,27.0,27.0,42.8,8.6,35.9,62.1,46.8
2,South Andaman,Andaman & Nicobar Islands,967,99.6,89.3,91.9,1.2,86.7,57.5,17.1,98.2,99.5,-76.3,21.1,12.6,17.4,10.0,39.0,57.7,19.6

In [29]:
df.isnull().sum()

District                0
State                   0
Sex_Ratio               0
Electricity             0
Sanitation              0
Clean_Fuel              0
Health_Insurance        0
Women_Literacy          0
Women_Schooling         0
Child_Marriage          0
Menstrual_Hygiene       0
Institutional_Births    0
Vaccination             0
Stunted                 0
Wasted                  0
Underweight             0
Low_BMI                 0
Obese                   0
Anaemia                 0
Tobacco_Use             0
dtype: int64

In [32]:
df.dtypes

District                    str
State                       str
Sex_Ratio                 int64
Electricity             float64
Sanitation              float64
Clean_Fuel              float64
Health_Insurance        float64
Women_Literacy          float64
Women_Schooling         float64
Child_Marriage          float64
Menstrual_Hygiene       float64
Institutional_Births    float64
Vaccination                 str
Stunted                 float64
Wasted                  float64
Underweight             float64
Low_BMI                 float64
Obese                   float64
Anaemia                 float64
Tobacco_Use             float64
dtype: object

In [36]:
state_sex_ratio = df.groupby('State')['Sex_Ratio'].mean().reset_index()
state_sex_ratio.columns = ['State', 'Avg_Sex_Ratio']

# 1000 se zyada = females zyada, kam = males zyada
state_sex_ratio['Dominance'] = state_sex_ratio['Avg_Sex_Ratio'].apply(
    lambda x: '👩 Females More' if x > 1000 else '👨 Males More'
)

state_sex_ratio.sort_values('Avg_Sex_Ratio', ascending=False).head(5)

            State  Avg_Sex_Ratio       Dominance
0    Lakshadweep     1187.000000  👩 Females More
26     Puducherry    1122.750000  👩 Females More
16         Kerala    1116.285714  👩 Females More
30     Tamil Nadu    1107.875000  👩 Females More
34    Uttarakhand    1095.923077  👩 Females More

In [35]:
df.groupby('State')['Child_Marriage'].mean().reset_index()\
  .sort_values('Child_Marriage', ascending=False)\
  .head(5)

          State  Child_Marriage
5         Bihar       41.071053
35  West Bengal       39.920000
32      Tripura       39.675000
14    Jharkhand       32.345833
4         Assam       30.509091

In [37]:
df.groupby('State')['Tobacco_Use'].mean().reset_index()\
  .sort_values('Tobacco_Use', ascending=False)\
  .head(5)

                        State  Tobacco_Use
22                    Mizoram    62.625000
32                    Tripura    51.225000
1   Andaman & Nicobar Islands    43.300000
20                    Manipur    42.277778
21                  Meghalaya    27.872727

In [38]:
df.groupby('State')['Health_Insurance'].mean().reset_index()\
  .sort_values('Health_Insurance', ascending=False)\
  .head(5)

             State  Health_Insurance
28       Rajasthan         88.436364
7     Chhattisgarh         73.185185
2   Andhra Pradesh         70.830769
21       Meghalaya         68.290909
30      Tamil Nadu         67.903125

In [39]:
df.groupby('State')['Electricity'].mean().reset_index()\
  .sort_values('Electricity', ascending=False)\
  .tail(5)

                State  Electricity
3   Arunachal Pradesh    94.865000
14          Jharkhand    93.450000
4               Assam    93.157576
21          Meghalaya    91.436364
33      Uttar Pradesh    91.149333