In [72]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [73]:
df = pd.read_csv(r"C:\Users\ADITYA GUPTA\Downloads\Online Casino Games Dataset\online_casino_games_dataset_v2.csv")

In [75]:
df.head(5)

,casino,game,provider,rtp,volatility,jackpot,country_availability,min_bet,max_win,game_type,game_category,license_jurisdiction,release_year,currency,mobile_compatible,free_spins_feature,bonus_buy_available,max_multiplier,languages,last_updated
0,Guts Casino,Texas Hold'em Bonus,Saucify,98.83,Medium,NaN,AR|BR|CH|CO|CY|DE|EE|ES|IE|IL|KE|MT|NZ|PE|PT|R...,1.00,435957.16,poker,Video Poker,MGA,2021,SEK|USD,True,False,False,356.0,EN|ES|TR|IT|JA|DE|FR|CS,2024-09-20
1,Expekt,Mines,Playtech,98.05,Low,NaN,BG|HR|ID|LT|NO|PH|SE|TR,0.25,1396.15,crash,Crash,Curaçao,2018,NZD|BRL|CAD|SEK|AUD,True,False,False,206.0,EN|SV|TR|ZH|PT|ES|FR|JA,2024-02-03
2,Betinia,Mega Vault,Gamomat,95.43,Very High,NaN,CH|ES|GB|HU|ID|IE|IN|LT|NO|SE|SG|VN,0.10,1180.12,slot,3D Slot,Isle of Man,2014,NZD|AUD|BRL|GBP|CAD,True,True,False,1787.0,EN|DE|FI|HU|PT|ZH|FR|JA,2024-07-09
3,Pinnacle,Casino Hold'em Pro,4ThePlayer,99.50,Medium,NaN,BE|BR|MY|NG|PL,0.05,236507.50,poker,Three Card Poker,MGA,2023,DKK|NZD|SEK,True,False,False,369.0,EN|ES|SV|DA|CS|FR|ZH|FI|NO|PT|HU|KO,2024-06-27
4,Winnerz,Solar Star Xtreme,Hacksaw Gaming,97.18,High,NaN,CL|KE|PT|SG|SI,0.20,1093.45,slot,Jackpot Slot,MGA,2022,NOK|GBP,True,True,False,1970.0,EN|JA|PT|KO|ES,2024-04-24

In [76]:
df['jackpot'].unique()

<StringArray>
[nan, 'Local', 'Fixed', 'Progressive']
Length: 4, dtype: str

In [74]:
df.isnull().sum()

casino                        0
game                          0
provider                      0
rtp                           0
volatility                    0
jackpot                 1071543
country_availability          0
min_bet                       0
max_win                       0
game_type                     0
game_category                 0
license_jurisdiction          0
release_year                  0
currency                      0
mobile_compatible             0
free_spins_feature            0
bonus_buy_available           0
max_multiplier           213814
languages                     0
last_updated                  0
dtype: int64

In [77]:
df['jackpot'] = df['jackpot'].fillna('Not Specified')

In [78]:
df['max_multiplier'] = df['max_multiplier'].fillna(df['max_multiplier'].mode()[0])

In [79]:
df.isnull().sum()

casino                  0
game                    0
provider                0
rtp                     0
volatility              0
jackpot                 0
country_availability    0
min_bet                 0
max_win                 0
game_type               0
game_category           0
license_jurisdiction    0
release_year            0
currency                0
mobile_compatible       0
free_spins_feature      0
bonus_buy_available     0
max_multiplier          0
languages               0
last_updated            0
dtype: int64

In [80]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200000 entries, 0 to 1199999
Data columns (total 20 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   casino                1200000 non-null  str
 1   game                  1200000 non-null  str
 2   provider              1200000 non-null  str
 3   rtp                   1200000 non-null  float64
 4   volatility            1200000 non-null  str
 5   jackpot               1200000 non-null  str
 6   country_availability  1200000 non-null  str
 7   min_bet               1200000 non-null  float64
 8   max_win               1200000 non-null  float64
 9   game_type             1200000 non-null  str
 10  game_category         1200000 non-null  str
 11  license_jurisdiction  1200000 non-null  str
 12  release_year          1200000 non-null  int64
 13  currency              1200000 non-null  str
 14  mobile_compatible     1200000 non-null  bool
 15  free_spins_feature    1200000 non-null  bool
 16  bonus_buy_available   1200000 non-null  bool
 17  max_multiplier        1200000 non-null  float64
 18  languages             1200000 non-null  str
 19  last_updated          1200000 non-null  str
dtypes: bool(3), float64(4), int64(1), str(12)
memory usage: 159.1 MB

In [81]:
df['max_multiplier'] = df['max_multiplier'].astype(float)

In [82]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200000 entries, 0 to 1199999
Data columns (total 20 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   casino                1200000 non-null  str
 1   game                  1200000 non-null  str
 2   provider              1200000 non-null  str
 3   rtp                   1200000 non-null  float64
 4   volatility            1200000 non-null  str
 5   jackpot               1200000 non-null  str
 6   country_availability  1200000 non-null  str
 7   min_bet               1200000 non-null  float64
 8   max_win               1200000 non-null  float64
 9   game_type             1200000 non-null  str
 10  game_category         1200000 non-null  str
 11  license_jurisdiction  1200000 non-null  str
 12  release_year          1200000 non-null  int64
 13  currency              1200000 non-null  str
 14  mobile_compatible     1200000 non-null  bool
 15  free_spins_feature    1200000 non-null  bool
 16  bonus_buy_available   1200000 non-null  bool
 17  max_multiplier        1200000 non-null  float64
 18  languages             1200000 non-null  str
 19  last_updated          1200000 non-null  str
dtypes: bool(3), float64(4), int64(1), str(12)
memory usage: 159.1 MB

In [85]:
df.head(5)

,casino,game,provider,rtp,volatility,jackpot,country_availability,min_bet,max_win,game_type,game_category,license_jurisdiction,release_year,currency,mobile_compatible,free_spins_feature,bonus_buy_available,max_multiplier,languages,last_updated
0,Guts Casino,Texas Hold'em Bonus,Saucify,98.83,Medium,Not Specified,AR|BR|CH|CO|CY|DE|EE|ES|IE|IL|KE|MT|NZ|PE|PT|R...,1.00,435957.16,poker,Video Poker,MGA,2021,SEK|USD,True,False,False,356.0,EN|ES|TR|IT|JA|DE|FR|CS,2024-09-20
1,Expekt,Mines,Playtech,98.05,Low,Not Specified,BG|HR|ID|LT|NO|PH|SE|TR,0.25,1396.15,crash,Crash,Curaçao,2018,NZD|BRL|CAD|SEK|AUD,True,False,False,206.0,EN|SV|TR|ZH|PT|ES|FR|JA,2024-02-03
2,Betinia,Mega Vault,Gamomat,95.43,Very High,Not Specified,CH|ES|GB|HU|ID|IE|IN|LT|NO|SE|SG|VN,0.10,1180.12,slot,3D Slot,Isle of Man,2014,NZD|AUD|BRL|GBP|CAD,True,True,False,1787.0,EN|DE|FI|HU|PT|ZH|FR|JA,2024-07-09
3,Pinnacle,Casino Hold'em Pro,4ThePlayer,99.50,Medium,Not Specified,BE|BR|MY|NG|PL,0.05,236507.50,poker,Three Card Poker,MGA,2023,DKK|NZD|SEK,True,False,False,369.0,EN|ES|SV|DA|CS|FR|ZH|FI|NO|PT|HU|KO,2024-06-27
4,Winnerz,Solar Star Xtreme,Hacksaw Gaming,97.18,High,Not Specified,CL|KE|PT|SG|SI,0.20,1093.45,slot,Jackpot Slot,MGA,2022,NOK|GBP,True,True,False,1970.0,EN|JA|PT|KO|ES,2024-04-24

In [87]:
df['last_updated'] = pd.to_datetime(df['last_updated'], format='%Y-%m-%d')

In [90]:
df['last_updated'].dtype

dtype('<M8[us]')

In [91]:
df.duplicated().sum()

np.int64(0)