In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [16]:
Cust = pd.read_csv(r"C:\Users\ADITYA GUPTA\Downloads\Data\Retail Fashion Data\customer_data.csv")
Prod = pd.read_csv(r"C:\Users\ADITYA GUPTA\Downloads\Data\Retail Fashion Data\product_data.csv")
Sales = pd.read_csv(r"C:\Users\ADITYA GUPTA\Downloads\Data\Retail Fashion Data\sales_data.csv")
Store = pd.read_csv(r"C:\Users\ADITYA GUPTA\Downloads\Data\Retail Fashion Data\store_data.csv")

merged_data = pd.merge(Sales, Cust, on='customer_id', how='left')
merged_data = pd.merge(merged_data, Prod, on='product_id', how='left')
merged_data = pd.merge(merged_data, Store, on='store_id', how='left')

In [17]:
merged_data.head()

,transaction_id,date,product_id,store_id,customer_id,quantity,discount,returned,age,gender,...,category,color,size,season,supplier,cost_price,list_price,store_name,region,store_size_m2
0,T0000001,8/2/2023,P004681,S004,C010043,3,0.0,0,50.0,Male,...,Shoes,NaN,S,Summer,suppliera,8.63,168.10,Online,Online,950.0
1,T0000002,8/16/2020,P006662,S003,C022472,1,0.0,0,22.0,Other,...,Accessories,Blue,M,Winter,supplierb,71.93,121.79,Faro Outlet,Algarve,336.0
2,T0000003,2/21/2020,P043402,S005,C016135,4,0.0,0,19.0,Other,...,Shoes,Red,L,Spring,suppliera,78.59,83.97,Coimbra Boutique,Coimbra,238.0
3,T0000004,2/27/2024,P029875,S003,C005605,3,NaN,1,69.0,Male,...,Shoes,Blue,L,Winter,supplierd,28.10,136.73,Faro Outlet,Algarve,336.0
4,T0000005,7/17/2021,P002476,S003,C005857,4,0.0,0,33.0,Other,...,Tops,Blue,M,Fall,supplierd,65.12,23.31,Faro Outlet,Algarve,336.0

In [18]:
df = merged_data.copy()
df.head()

,transaction_id,date,product_id,store_id,customer_id,quantity,discount,returned,age,gender,...,category,color,size,season,supplier,cost_price,list_price,store_name,region,store_size_m2
0,T0000001,8/2/2023,P004681,S004,C010043,3,0.0,0,50.0,Male,...,Shoes,NaN,S,Summer,suppliera,8.63,168.10,Online,Online,950.0
1,T0000002,8/16/2020,P006662,S003,C022472,1,0.0,0,22.0,Other,...,Accessories,Blue,M,Winter,supplierb,71.93,121.79,Faro Outlet,Algarve,336.0
2,T0000003,2/21/2020,P043402,S005,C016135,4,0.0,0,19.0,Other,...,Shoes,Red,L,Spring,suppliera,78.59,83.97,Coimbra Boutique,Coimbra,238.0
3,T0000004,2/27/2024,P029875,S003,C005605,3,NaN,1,69.0,Male,...,Shoes,Blue,L,Winter,supplierd,28.10,136.73,Faro Outlet,Algarve,336.0
4,T0000005,7/17/2021,P002476,S003,C005857,4,0.0,0,33.0,Other,...,Tops,Blue,M,Fall,supplierd,65.12,23.31,Faro Outlet,Algarve,336.0

In [19]:
df.columns

Index(['transaction_id', 'date', 'product_id', 'store_id', 'customer_id',
       'quantity', 'discount', 'returned', 'age', 'gender', 'city', 'email',
       'category', 'color', 'size', 'season', 'supplier', 'cost_price',
       'list_price', 'store_name', 'region', 'store_size_m2'],
      dtype='str')

In [20]:
df.isnull().sum()

transaction_id       0
date                 0
product_id           0
store_id             0
customer_id       1844
quantity             0
discount          2583
returned             0
age               1844
gender            1844
city              1844
email             2836
category           200
color             1163
size               200
season             200
supplier           200
cost_price         200
list_price         200
store_name         200
region             200
store_size_m2      200
dtype: int64

In [21]:
df = df.dropna()

In [22]:
df.isnull().sum()

transaction_id    0
date              0
product_id        0
store_id          0
customer_id       0
quantity          0
discount          0
returned          0
age               0
gender            0
city              0
email             0
category          0
color             0
size              0
season            0
supplier          0
cost_price        0
list_price        0
store_name        0
region            0
store_size_m2     0
dtype: int64

In [23]:
df.duplicated().sum()

np.int64(0)

In [26]:
df.shape

(43531, 22)

In [29]:
df.head(3)

,transaction_id,date,product_id,store_id,customer_id,quantity,discount,returned,age,gender,...,category,color,size,season,supplier,cost_price,list_price,store_name,region,store_size_m2
1,T0000002,8/16/2020,P006662,S003,C022472,1,0.0,0,22.0,Other,...,Accessories,Blue,M,Winter,supplierb,71.93,121.79,Faro Outlet,Algarve,336.0
2,T0000003,2/21/2020,P043402,S005,C016135,4,0.0,0,19.0,Other,...,Shoes,Red,L,Spring,suppliera,78.59,83.97,Coimbra Boutique,Coimbra,238.0
4,T0000005,7/17/2021,P002476,S003,C005857,4,0.0,0,33.0,Other,...,Tops,Blue,M,Fall,supplierd,65.12,23.31,Faro Outlet,Algarve,336.0

In [27]:
df.describe()

,quantity,discount,returned,age,cost_price,list_price,store_size_m2
count,43531.000000,43531.000000,43531.000000,43531.000000,43531.000000,43531.000000,43531.000000
mean,2.506283,0.058253,0.099217,42.523673,42.537756,105.221046,484.853759
std,1.118717,0.088131,0.298956,15.559462,21.708805,54.750535,300.377324
min,1.000000,0.000000,0.000000,16.000000,5.000000,10.000000,179.000000
25%,2.000000,0.000000,0.000000,29.000000,23.830000,58.270000,238.000000
50%,3.000000,0.000000,0.000000,43.000000,42.490000,105.430000,336.000000
75%,4.000000,0.100000,0.000000,56.000000,61.395000,152.450000,728.000000
max,4.000000,0.300000,1.000000,69.000000,80.000000,199.990000,950.000000